import { Modal } from '@/components';
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Trello 2.O AI Clone',
  description: 'Generated by GismoDev',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
