import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Trellop 2.O AI Clone',
  description: 'Generated by GismoDev',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
